services:
  mysql:
      container_name: mysql
      image: mariadb:11.1.2
      ports:
        - "3306:3306"
      environment:
        MYSQL_USER: "root"
        MYSQL_PASSWORD: ""
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
      volumes:
        - ./data/db:/var/lib/mysql
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /etc/hosts:/etc/hosts
      - ./config/nginx-proxy.conf:/etc/nginx/conf.d/nginx-proxy.conf
      - ./config/index.html:/usr/share/nginx/html/index.html